language: node_js
node_js:
  - 7

cache:
  directories:
    - node_modules

before_install:
  - npm i yarn nyc -g

install:
  - yarn --pure-lockfile

before_script:
  - yarn compile

script:
  - yarn lint
  - yarn test
  - nyc report -r=text-lcov | ./node_modules/.bin/codecov

branches:
  only:
    - master
    - /^greenkeeper/.*$/
